/* aOra Elite Activity Layer: importers, analytics, splits, records, gear, export. */
let activityFilterState={type:"all",from:"",to:"",minDistance:""};
let activityDetailCharts=[];
const GEAR_TYPES=["shoes","bike","other"];

function activityRoutePoints(a){
  if(Array.isArray(a?.route_data)) return a.route_data.filter(p=>Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng)));
  return [];
}
function routeDistance(a,b){return typeof haversineM==="function"?haversineM(a,b):0;}
function activitySplits(a){
  const pts=activityRoutePoints(a); if(pts.length<2)return [];
  const splits=[]; let km=0,start=pts[0],acc=0,last=pts[0];
  for(let i=1;i<pts.length;i++){const d=routeDistance(last,pts[i])/1000; if(!Number.isFinite(d)||d>0.25){last=pts[i];continue;} acc+=d; km+=d;
    while(km>=1){const seconds=(new Date(pts[i].timestamp)-new Date(start.timestamp))/1000; splits.push({km:splits.length+1,pace:seconds}); start=pts[i]; acc=0; km-=1;} last=pts[i];
  }
  const total=a.distance_km||0; if(splits.length===0&&total>0&&a.duration_seconds)splits.push({km:total,pace:a.duration_seconds/total});
  return splits;
}
function activityMetricsForRange(list,from,to){return list.filter(a=>{const d=new Date(a.activity_at||a.created_at);return (!from||d>=new Date(from))&&(!to||d<=new Date(to+"T23:59:59"));});}
function activityApplyFilters(){
  const type=$("activityFilterType")?.value||"all",from=$("activityFilterFrom")?.value||"",to=$("activityFilterTo")?.value||"",min=Number($("activityFilterMin")?.value)||0;
  activityFilterState={type,from,to,minDistance:min};
  const filtered=activities.filter(a=>(type==="all"||a.type===type)&&(!from||new Date(a.activity_at)>=new Date(from))&&(!to||new Date(a.activity_at)<=new Date(to+"T23:59:59"))&&(!min||Number(a.distance_km||0)>=min));
  renderActivityFeedFiltered(filtered); renderEliteAnalytics(filtered);
}
function renderActivityFeedFiltered(list){
 const el=$("activityFeed");if(!el)return; el.innerHTML=list.length?list.map(activityCard).join(""):`<div class="empty-state">${escapeHtml(t("activity.noData"))}</div>`;
}
function activityWeekKey(d){const x=new Date(d);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);x.setHours(0,0,0,0);return x.toISOString().slice(0,10);}
function sum(list,key){return list.reduce((s,a)=>s+(Number(a[key])||0),0);}
function formatHours(sec){const h=(Number(sec)||0)/3600;return h<10?h.toFixed(1):Math.round(h).toString();}
function renderEliteAnalytics(list=activities){
 const now=new Date(), start=new Date(now); start.setDate(now.getDate()-6); const week=list.filter(a=>new Date(a.activity_at)>=start);
 const monthStart=new Date(now.getFullYear(),now.getMonth(),1); const month=list.filter(a=>new Date(a.activity_at)>=monthStart);
 const set=(id,v)=>{const e=$(id);if(e)e.textContent=v;};
 set("eliteWeekVolume",`${formatHours(sum(week,"duration_seconds"))} h`);set("eliteWeekDistance",`${sum(week,"distance_km").toFixed(1)} km`);set("eliteWeekElevation",`${Math.round(sum(week,"elevation_gain_m"))} m`);set("eliteLoad",Math.round(trainingLoad(week)));
 renderHeatmap(list); renderRecords(list); renderTrends(list);
}
function trainingLoad(list){return list.reduce((s,a)=>{const dur=(Number(a.duration_seconds)||0)/60;const intensity=(Number(a.avg_heart_rate)||0)>0?Math.min(2,Math.max(.7,(Number(a.avg_heart_rate)||120)/140)):((Number(a.pace_seconds_per_km)||0)>0?Math.min(1.8,Math.max(.7,300/(Number(a.pace_seconds_per_km)||300))):1);return s+dur*intensity;},0);}
function renderHeatmap(list){const wrap=$("activityHeatmap");if(!wrap)return;const end=new Date();end.setHours(0,0,0,0);const cells=[];for(let i=83;i>=0;i--){const d=new Date(end);d.setDate(end.getDate()-i);const key=d.toISOString().slice(0,10);const n=list.filter(a=>(a.activity_at||a.created_at).slice(0,10)===key).length;cells.push(`<span class="heat-cell h${Math.min(n,4)}" title="${key}: ${n}"></span>`);}wrap.innerHTML=cells.join("");}
function renderRecords(list){
 const candidates=[{label:"1 km",km:1},{label:"5 km",km:5},{label:"10 km",km:10},{label:"Longest",km:0}];
 const out=[]; candidates.forEach(c=>{let arr=list.filter(a=>Number(a.distance_km)>=(c.km||0.001)); if(!arr.length)return; if(c.km){arr=arr.filter(a=>a.type==="running"||a.type==="trail"||a.type==="walking"); if(!arr.length)return; const valid=arr.filter(a=>Number(a.distance_km)>=c.km&&Number(a.duration_seconds)>0); if(!valid.length)return; const best=valid.sort((a,b)=>(a.duration_seconds/a.distance_km)-(b.duration_seconds/b.distance_km))[0]; out.push(`<div><b>${c.label} PR</b><span>${formatPace(best.duration_seconds/best.distance_km)} · ${escapeHtml(formatActivityDate(best))}</span></div>`);}else{const best=arr.sort((a,b)=>(b.distance_km||0)-(a.distance_km||0))[0];out.push(`<div><b>Longest activity</b><span>${formatDistance(best.distance_km)} · ${escapeHtml(formatActivityDate(best))}</span></div>`);}}); $("activityRecords").innerHTML=out.join("")||`<span class="muted">${escapeHtml(t("activity.noData"))}</span>`;
}
function formatActivityDate(a){return new Date(a.activity_at||a.created_at).toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"});}
function renderTrends(list){const ctx=$("activityTrendChart");if(!ctx||typeof Chart==="undefined")return; if(window.activityTrendChart)window.activityTrendChart.destroy();const labels=[],vals=[];for(let i=7;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i*7);const end=new Date(d);end.setDate(d.getDate()+6);labels.push(`W-${i}`);vals.push(list.filter(a=>{const x=new Date(a.activity_at);return x>=d&&x<=end;}).reduce((s,a)=>s+(Number(a.distance_km)||0),0));}window.activityTrendChart=new Chart(ctx,{type:"line",data:{labels,datasets:[{label:t("activity.distance"),data:vals,tension:.35,fill:true}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}});}
function renderEliteDetail(a){const pts=activityRoutePoints(a);const splits=activitySplits(a);let mapHtml=pts.length?`<div id="activityDetailMap" class="activity-detail-map"></div>`:"";const splitHtml=splits.length?`<div class="split-list"><h4>${escapeHtml(t("activity.splits"))}</h4>${splits.map(s=>`<div><span>${s.km} km</span><b>${formatPace(s.pace)}</b></div>`).join("")}</div>`:"";const exportBtns=`<div class="detail-actions"><button class="secondary" id="exportActivityGpx">GPX</button><button class="secondary" id="exportActivityJson">JSON</button></div>`;const html=`${mapHtml}<div class="activity-detail-grid"><div><span>${escapeHtml(t("activity.duration"))}</span><b>${formatDuration(a.duration_seconds)}</b></div><div><span>${escapeHtml(t("activity.distance"))}</span><b>${formatDistance(a.distance_km)}</b></div><div><span>${escapeHtml(t("activity.pace"))}</span><b>${formatPace(a.pace_seconds_per_km)}</b></div><div><span>${escapeHtml(t("activity.calories"))}</span><b>${Math.round(a.calories||0)} kcal</b></div><div><span>Elevation</span><b>${Math.round(a.elevation_gain_m||0)} m</b></div><div><span>Speed</span><b>${Number(a.avg_speed_kmh||0).toFixed(1)} km/h</b></div></div>${splitHtml}${exportBtns}`;$("activityModalBody").insertAdjacentHTML("afterbegin",html); if(pts.length)setTimeout(()=>drawDetailMap(pts),30);$("exportActivityGpx")?.addEventListener("click",()=>downloadText(toGPX(a),`${slugify(a.title||a.type)}.gpx`,`application/gpx+xml`));$("exportActivityJson")?.addEventListener("click",()=>downloadText(JSON.stringify(a,null,2),`${slugify(a.title||a.type)}.json`,`application/json`));}
function drawDetailMap(points){const el=$("activityDetailMap");if(!el||typeof L==="undefined")return;const m=L.map(el,{zoomControl:false}).setView([points[0].lat,points[0].lng],14);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(m);const line=L.polyline(points.map(p=>[p.lat,p.lng]),{weight:5}).addTo(m);m.fitBounds(line.getBounds(),{padding:[20,20]});}
function slugify(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"activity";}
function downloadText(text,name,type){const blob=new Blob([text],{type});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function toGPX(a){const pts=activityRoutePoints(a);const trk=pts.map(p=>`<trkpt lat="${p.lat}" lon="${p.lng}">${p.altitude!=null?`<ele>${p.altitude}</ele>`:""}<time>${p.timestamp||""}</time></trkpt>`).join("");return `<?xml version="1.0"?><gpx version="1.1" creator="aOra Coach" xmlns="http://www.topografix.com/GPX/1/1"><trk><name>${escapeHtml(a.title||a.type)}</name><trkseg>${trk}</trkseg></trk></gpx>`;}
async function parseActivityFile(file){const ext=file.name.toLowerCase().split(".").pop();if(ext==="gpx"||ext==="tcx")return parseXmlActivity(await file.text(),ext);if(ext==="fit")return parseFitActivity(await file.arrayBuffer());throw new Error("Supported files: GPX, FIT, TCX");}
function parseXmlActivity(text,ext){const xml=new DOMParser().parseFromString(text,"application/xml");if(xml.querySelector("parsererror"))throw new Error("Invalid activity file");const ns=ext==="gpx"?"http://www.topografix.com/GPX/1/1":"http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2";let pts=[];if(ext==="gpx"){pts=[...xml.getElementsByTagName("trkpt")].map(p=>({lat:Number(p.getAttribute("lat")),lng:Number(p.getAttribute("lon")),altitude:Number(p.querySelector("ele")?.textContent)||null,timestamp:p.querySelector("time")?.textContent||null}));}else{pts=[...xml.getElementsByTagName("Trackpoint")].map(p=>({lat:Number(p.querySelector("LatitudeDegrees")?.textContent),lng:Number(p.querySelector("LongitudeDegrees")?.textContent),altitude:Number(p.querySelector("AltitudeMeters")?.textContent)||null,timestamp:p.querySelector("Time")?.textContent||null})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng));}return normalizeImportedRoute(pts,ext);}
async function parseFitActivity(buf){if(typeof FitParser==="undefined")throw new Error("FIT parser unavailable. Reload the app and try again.");const parser=new FitParser({mode:"cascade",speedUnit:"km/h",lengthUnit:"km",elapsedRecordField:true});const data=await new Promise((resolve,reject)=>parser.parse(buf,(err,res)=>err?reject(err):resolve(res)));const records=data.records||data.activity?.records||[];const pts=records.map(r=>({lat:Number(r.position_latitude??r.position_lat),lng:Number(r.position_longitude??r.position_long),altitude:Number(r.altitude??r.enhanced_altitude)||null,timestamp:r.timestamp instanceof Date?r.timestamp.toISOString():(r.timestamp||null),speed:Number(r.speed??r.enhanced_speed)||null,heart_rate:Number(r.heart_rate)||null})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng));return normalizeImportedRoute(pts,"fit",data);}
function normalizeImportedRoute(pts,source,raw={}){let dist=0,gain=0,loss=0;const speeds=[];for(let i=1;i<pts.length;i++){const d=haversineM(pts[i-1],pts[i]);if(d<300)dist+=d;const z=Number(pts[i].altitude)-Number(pts[i-1].altitude);if(Number.isFinite(z)&&Math.abs(z)<30){if(z>0)gain+=z;else loss-=z;}if(Number.isFinite(pts[i].speed))speeds.push(pts[i].speed);}const start=pts[0]?.timestamp,end=pts.at(-1)?.timestamp;const dur=start&&end?Math.max(0,(new Date(end)-new Date(start))/1000):null;const type=source==="fit"?inferFitType(raw):"running";return {type,title:activityTypeLabel(type),activity_at:start||new Date().toISOString(),started_at:start,ended_at:end,duration_seconds:dur,distance_km:dist/1000,pace_seconds_per_km:dist>0&&dur?dur/(dist/1000):null,avg_speed_kmh:dur?dist/1000/(dur/3600):null,max_speed_kmh:speeds.length?Math.max(...speeds):null,elevation_gain_m:gain,elevation_loss_m:loss,route_data:pts,source:"file",extraction_method:"file",raw_data:{format:source,record_count:pts.length}};}
function inferFitType(data){const s=String(data.sessions?.[0]?.sport||data.activity?.sport||"").toLowerCase();return s.includes("cycling")?"cycling":s.includes("walking")?"walking":s.includes("hiking")?"hiking":s.includes("running")?"running":"other";}
async function saveImportedActivity(d){const row={...d,user_id:user.id,type:d.type||"other",raw_data:d.raw_data||{},source:"file",extraction_method:"file",confidence:1,image_url:null};const saved=await insertActivity(row);await loadActivities(user.id);toast(t("activity.saved"),"ok");return saved;}
function openFileImport(){$("activityFileInput")?.click();}
async function handleFileImport(file){if(!file)return;try{$("activityFileStatus").textContent=t("activity.fileParsing");const d=await parseActivityFile(file);await saveImportedActivity(d);$("activityFileStatus").textContent=t("activity.fileImported");}catch(e){$("activityFileStatus").textContent=e.message||t("activity.fileError");toast(e.message||t("activity.fileError"),"error");}}
async function renderGear(){const el=$("#gearList");if(!el)return;let rows=[];try{rows=await loadGear(user.id);}catch(_e){rows=[];}el.innerHTML=rows.length?rows.map(g=>{const km=sum(activities.filter(a=>a.gear_id===g.id),"distance_km");const max=Number(g.max_distance_km)||0;const pct=max?Math.min(100,km/max*100):0;return `<div class="gear-row"><div><b>${escapeHtml(g.name)}</b><span>${escapeHtml([g.brand,g.model].filter(Boolean).join(" · "))}</span></div><div class="gear-mileage"><b>${km.toFixed(0)} km</b>${max?`<span>${Math.round(pct)}% of ${max} km</span>`:""}</div></div>`;}).join(""):`<span class="muted">${escapeHtml(t("activity.noGear"))}</span>`;}
function bindEliteActivities(){
 const gearForm=$("#gearForm"); $("#gearAddBtn")?.addEventListener("click",()=>gearForm?.classList.toggle("hidden")); gearForm?.addEventListener("submit",async e=>{e.preventDefault();try{const fd=new FormData(e.currentTarget);await saveGear({user_id:user.id,name:String(fd.get("name")||"").trim(),type:fd.get("type")||"other",brand:String(fd.get("brand")||"").trim()||null,model:String(fd.get("model")||"").trim()||null,max_distance_km:fd.get("max_distance_km")?Number(fd.get("max_distance_km")):null,active:true});e.currentTarget.reset();e.currentTarget.classList.add("hidden");await renderGear();toast(t("activity.gearSaved"),"ok");}catch(err){toast(err.message||"Gear error","error");}}); $("activityApplyFilters")?.addEventListener("click",activityApplyFilters);$("activityClearFilters")?.addEventListener("click",()=>{["activityFilterFrom","activityFilterTo","activityFilterMin"].forEach(id=>{if($(id))$(id).value=""});if($("activityFilterType"))$("activityFilterType").value="all";activityApplyFilters();});$("activityImportFileBtn")?.addEventListener("click",openFileImport);$("activityFileInput")?.addEventListener("change",async e=>{for(const file of [...(e.target.files||[])]) await handleFileImport(file); e.target.value="";});$("activityExportAll")?.addEventListener("click",()=>downloadText(JSON.stringify(activities,null,2),"aora-activities.json","application/json"));renderEliteAnalytics(activities);renderGear();
}
