const I18N_SUPPORTED=["en","es","fr","pt","de","zh","ar","hi","ru","id","ja","ko","tr"];
const I18N_META={en:{name:"English",rtl:false},es:{name:"Español",rtl:false},fr:{name:"Français",rtl:false},pt:{name:"Português",rtl:false},de:{name:"Deutsch",rtl:false},zh:{name:"中文",rtl:false},ar:{name:"العربية",rtl:true},hi:{name:"हिन्दी",rtl:false},ru:{name:"Русский",rtl:false},id:{name:"Bahasa Indonesia",rtl:false},ja:{name:"日本語",rtl:false},ko:{name:"한국어",rtl:false},tr:{name:"Türkçe",rtl:false}};
let currentLanguage="en",translationsCache={};
function normalizeLanguage(v){const b=(v||"").toLowerCase().split("-")[0].split("_")[0];return I18N_SUPPORTED.includes(b)?b:"en"}
function detectLanguage(){const saved=localStorage.getItem("aora_language");if(saved&&I18N_SUPPORTED.includes(saved))return saved;for(const x of (navigator.languages||[navigator.language])){const n=normalizeLanguage(x);if(I18N_SUPPORTED.includes(n))return n}return"en"}
async function loadLanguage(lang){lang=normalizeLanguage(lang);if(!translationsCache[lang]){const r=await fetch(`i18n/${lang}.json`,{cache:"no-store"});if(!r.ok)throw Error(`Language file error ${r.status}`);translationsCache[lang]=await r.json()}currentLanguage=lang;localStorage.setItem("aora_language",lang);document.documentElement.lang=lang;document.documentElement.dir=I18N_META[lang].rtl?"rtl":"ltr";applyTranslations();renderLanguageSelectors();document.dispatchEvent(new CustomEvent("aora-language-changed",{detail:{language:lang,name:I18N_META[lang].name}}));if(typeof updateLanguageProfile==="function")await updateLanguageProfile()}
function t(key,vars={}){const d=translationsCache[currentLanguage]||translationsCache.en||{};return String(d[key]??key).replace(/\{(\w+)\}/g,(_,k)=>vars[k]??`{${k}}`)}
function applyTranslations(){document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=t(e.dataset.i18n));document.querySelectorAll("[data-i18n-placeholder]").forEach(e=>e.placeholder=t(e.dataset.i18nPlaceholder));document.querySelectorAll("[data-i18n-aria]").forEach(e=>e.setAttribute("aria-label",t(e.dataset.i18nAria)));document.querySelectorAll("[data-i18n-option]").forEach(e=>e.textContent=t(e.dataset.i18nOption))}
function renderLanguageSelectors(){["#languageSelect","#languageSelectAuth"].forEach(sel=>{const e=document.querySelector(sel);if(!e)return;e.innerHTML=I18N_SUPPORTED.map(x=>`<option value="${x}">${I18N_META[x].name}</option>`).join("");e.value=currentLanguage})}
async function updateLanguageProfile(){if(typeof user==="undefined"||!user||typeof saveProfile!=="function"||!profile)return;if(profile.language===currentLanguage)return;try{profile.language=currentLanguage;await saveProfile({id:user.id,language:currentLanguage})}catch(_){}}
async function initI18n(){await loadLanguage(detectLanguage())}
