-- Seed catalog for Superhuman Coach.
-- IMPORTANT: affiliate_urls are intentionally empty. Replace them only with affiliate URLs
-- from programs you are actually approved for. destination_urls are ordinary merchant/search
-- destinations and do not generate commissions.
insert into public.affiliate_products
(slug,name,category,merchant_default,image_url,price_label,reason_key,tags,goals,levels,space_requirement,regions,destination_urls,affiliate_urls,priority,active)
values
('creatine-monohydrate','Creatine monohydrate','supplements','Amazon','assets/affiliate-creatine.svg','€15–€35 / $15–$35','aff.reason.creatine',array['strength','hypertrophy','performance'],array['strength','hypertrophy','recomp','power'],array['beginner','intermediate','advanced','elite'],'any',array['EU','US'],jsonb_build_object('EU','https://www.amazon.es/s?k=creatine+monohydrate','US','https://www.amazon.com/s?k=creatine+monohydrate'),'{}',80,true),
('protein','Protein powder','supplements','Amazon','assets/affiliate-protein.svg','€25–€55 / $25–$55','aff.reason.protein',array['protein','hypertrophy','recomp'],array['hypertrophy','recomp','strength'],array['beginner','intermediate','advanced','elite'],'any',array['EU','US'],jsonb_build_object('EU','https://www.amazon.es/s?k=whey+protein','US','https://www.amazon.com/s?k=whey+protein'),'{}',75,true),
('adjustable-dumbbells','Adjustable dumbbells','equipment','Amazon','assets/affiliate-dumbbells.svg','€150–€450 / $150–$450','aff.reason.dumbbells',array['home gym','strength','hypertrophy'],array['strength','hypertrophy','recomp'],array['beginner','intermediate','advanced','elite'],'small',array['EU','US'],jsonb_build_object('EU','https://www.amazon.es/s?k=mancuernas+ajustables','US','https://www.amazon.com/s?k=adjustable+dumbbells'),'{}',70,true),
('resistance-bands','Resistance band set','equipment','Decathlon','assets/affiliate-bands.svg','€15–€45','aff.reason.bands',array['portable','small space','home gym'],array['strength','hypertrophy','recomp','power'],array['beginner','intermediate','advanced','elite'],'small',array['EU'],jsonb_build_object('EU','https://www.decathlon.es/es/search?Ntt=bandas%20elasticas'),'{}',65,true),
('foam-roller','Foam roller','recovery','Decathlon','assets/affiliate-recovery.svg','€15–€45','aff.reason.roller',array['recovery','mobility'],array['strength','hypertrophy','recomp','power'],array['beginner','intermediate','advanced','elite'],'small',array['EU'],jsonb_build_object('EU','https://www.decathlon.es/es/search?Ntt=foam%20roller'),'{}',55,true),
('massage-gun','Massage gun','recovery','Amazon','assets/affiliate-massage.svg','€50–€180 / $50–$180','aff.reason.massage',array['recovery','portable'],array['strength','hypertrophy','recomp','power'],array['intermediate','advanced','elite'],'small',array['EU','US'],jsonb_build_object('EU','https://www.amazon.es/s?k=massage+gun','US','https://www.amazon.com/s?k=massage+gun'),'{}',50,true),
('training-shoes','Training shoes','apparel','Amazon','assets/affiliate-shoes.svg','€60–€160 / $60–$160','aff.reason.shoes',array['training','stability'],array['strength','hypertrophy','recomp','power'],array['beginner','intermediate','advanced','elite'],'any',array['EU','US'],jsonb_build_object('EU','https://www.amazon.es/s?k=zapatillas+entrenamiento','US','https://www.amazon.com/s?k=training+shoes'),'{}',45,true),
('strength-book','Strength training reference book','books','Amazon','assets/affiliate-book.svg','€20–€45 / $20–$45','aff.reason.book',array['education','programming'],array['strength','hypertrophy','power'],array['intermediate','advanced','elite'],'any',array['EU','US'],jsonb_build_object('EU','https://www.amazon.es/s?k=strength+training+book','US','https://www.amazon.com/s?k=strength+training+book'),'{}',35,true)
on conflict (slug) do update set
  name=excluded.name, category=excluded.category, merchant_default=excluded.merchant_default,
  image_url=excluded.image_url, price_label=excluded.price_label, reason_key=excluded.reason_key,
  tags=excluded.tags, goals=excluded.goals, levels=excluded.levels, space_requirement=excluded.space_requirement,
  regions=excluded.regions, destination_urls=excluded.destination_urls, priority=excluded.priority, active=excluded.active;
