/* aOra GPS Activity Tracker — foreground mobile tracking with Leaflet + Supabase. */
const GPS_ACTIVITY_TYPES = ["running","walking","cycling","hiking","trail","elliptical","other"];
let gpsState = { status:"idle", type:"running", watchId:null, startedAt:null, pausedAt:null, elapsedBeforePause:0, points:[], lastAccepted:null, distanceM:0, elevationGainM:0, elevationLossM:0, speedSamples:[], movingDistanceM:0, movingTimeMs:0, map:null, line:null, marker:null, lastUi:0 };

function gpsReset(){ if(gpsState.watchId!==null){navigator.geolocation.clearWatch(gpsState.watchId);gpsState.watchId=null;} gpsState={...gpsState,status:"idle",points:[],distanceM:0,elevationGainM:0,elevationLossM:0,speedSamples:[],movingDistanceM:0,movingTimeMs:0,elapsedBeforePause:0,lastAccepted:null,lastUi:0,map:null,line:null,marker:null}; }
function haversineM(a,b){const R=6371008.8, p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180;const h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function gpsElapsed(){if(!gpsState.startedAt)return 0; const end=gpsState.status==="paused"&&gpsState.pausedAt?gpsState.pausedAt:Date.now(); return gpsState.elapsedBeforePause+Math.max(0,end-gpsState.startedAt);}
function gpsFormat(sec){sec=Math.max(0,Math.floor(sec/1000));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;}
function gpsActivityLabel(type){return t(`activity.gps.type.${type}`)||activityTypeLabel(type);}
function encodePolyline(points){let lastLat=0,lastLng=0,out="";const enc=n=>{let v=Math.round(n*1e5),s=v<0?~(v<<1):(v<<1),r="";while(s>=0x20){r+=String.fromCharCode((0x20|(s&0x1f))+63);s>>=5}return r+String.fromCharCode(s+63)};for(const p of points){const lat=Math.round(Number(p.lat)*1e5),lng=Math.round(Number(p.lng)*1e5);out+=enc(lat/1e5-lastLat/1e5)+enc(lng/1e5-lastLng/1e5);lastLat=lat;lastLng=lng}return out;}
function gpsCalories(type, kg, seconds, distanceM){const met={running:9.8,walking:3.5,cycling:7.5,hiking:6.0,trail:8.5,elliptical:6.0,other:5.0}[type]||5;const hours=seconds/3600000;return Math.max(0,met*(Number(kg)||70)*hours);}
function gpsMetricSpeed(){const vals=gpsState.speedSamples.filter(x=>Number.isFinite(x)&&x>=0&&x<20);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;}
function gpsPaceSec(){const km=gpsState.distanceM/1000, sec=gpsElapsed()/1000;return km>0.03?sec/km:null;}
function gpsUpdateUi(force=false){const now=Date.now();if(!force&&now-gpsState.lastUi<500)return;gpsState.lastUi=now;const elapsed=gpsElapsed(),km=gpsState.distanceM/1000,pace=gpsPaceSec(),speed=gpsMetricSpeed()*3.6;const set=(id,v)=>{const e=$(id);if(e)e.textContent=v;};set("gpsTime",gpsFormat(elapsed));set("gpsDistance",km.toFixed(km<10?2:1));set("gpsPace",pace?formatPace(pace):"—");set("gpsSpeed",speed?speed.toFixed(1):"—");set("gpsElevationGain",`${Math.round(gpsState.elevationGainM)} m`);set("gpsSignal",gpsState.lastAccepted?`${Math.round(gpsState.lastAccepted.accuracy)} m`:`—`);if(gpsState.line&&gpsState.map)gpsState.map.invalidateSize(false);}
function gpsRenderMap(){const el=$("gpsMap");if(!el||typeof L==="undefined")return;if(!gpsState.map){gpsState.map=L.map(el,{zoomControl:false,attributionControl:true}).setView([40.4168,-3.7038],14);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(gpsState.map);gpsState.line=L.polyline([],{weight:5}).addTo(gpsState.map);} if(gpsState.points.length){const latlng=gpsState.points.map(p=>[p.lat,p.lng]);gpsState.line.setLatLngs(latlng);if(!gpsState.marker)gpsState.marker=L.circleMarker(latlng[latlng.length-1],{radius:7}).addTo(gpsState.map);else gpsState.marker.setLatLng(latlng[latlng.length-1]);if(gpsState.points.length===1)gpsState.map.setView(latlng[0],16);else gpsState.map.fitBounds(gpsState.line.getBounds(),{padding:[24,24]});}}
function gpsHandlePosition(pos){if(gpsState.status!=="tracking")return;const c=pos.coords; if(!Number.isFinite(c.latitude)||!Number.isFinite(c.longitude))return; const p={lat:c.latitude,lng:c.longitude,timestamp:new Date(pos.timestamp||Date.now()).toISOString(),altitude:Number.isFinite(c.altitude)?c.altitude:null,accuracy:Number.isFinite(c.accuracy)?c.accuracy:null,speed:Number.isFinite(c.speed)?c.speed:null}; if(p.accuracy!=null&&p.accuracy>80)return;const prev=gpsState.lastAccepted;if(prev){const d=haversineM(prev,p),dt=(new Date(p.timestamp)-new Date(prev.timestamp))/1000; if(d<3&&dt<10)return; if(d>150&&dt<10)return; gpsState.distanceM+=d; if(d>=2 && d<=80 && dt>0 && dt<=30){gpsState.movingDistanceM+=d;gpsState.movingTimeMs+=dt*1000;} if(Number.isFinite(prev.altitude)&&Number.isFinite(p.altitude)){const dz=p.altitude-prev.altitude;if(Math.abs(dz)<=15){if(dz>0)gpsState.elevationGainM+=dz;else gpsState.elevationLossM+=-dz;}} if(Number.isFinite(p.speed)&&p.speed>=0&&p.speed<20)gpsState.speedSamples.push(p.speed);}
 gpsState.points.push(p);gpsState.lastAccepted=p;gpsRenderMap();gpsUpdateUi();}
function gpsHandleError(err){const key=err.code===1?"activity.gps.permission":err.code===2?"activity.gps.unavailable":"activity.gps.timeout";const e=$("gpsStatus");if(e)e.textContent=t(key);if(gpsState.status==="tracking")gpsUpdateUi(true);}
function gpsStart(){
if(!user){toast(t("auth.loginRequired"),"warn");return;}if(!navigator.geolocation)return toast(t("activity.gps.unsupported"),"error");gpsReset();gpsState.status="tracking";gpsState.type=$("gpsActivityType")?.value||"running";gpsState.startedAt=Date.now();gpsRenderMap();gpsUpdateUi(true);gpsState.watchId=navigator.geolocation.watchPosition(gpsHandlePosition,gpsHandleError,{enableHighAccuracy:true,maximumAge:3000,timeout:15000});$("gpsStartBtn").classList.add("hidden");$("gpsPauseBtn").classList.remove("hidden");$("gpsFinishBtn").classList.remove("hidden");$("gpsActivityType").disabled=true;$("gpsStatus").textContent=t("activity.gps.tracking");}
function gpsPause(){if(gpsState.status!=="tracking")return;gpsState.elapsedBeforePause=gpsElapsed();gpsState.pausedAt=Date.now();gpsState.status="paused";if(gpsState.watchId!==null){navigator.geolocation.clearWatch(gpsState.watchId);gpsState.watchId=null;}$("gpsPauseBtn").classList.add("hidden");$("gpsResumeBtn").classList.remove("hidden");$("gpsStatus").textContent=t("activity.gps.paused");gpsUpdateUi(true);}
function gpsResume(){if(gpsState.status!=="paused")return;gpsState.status="tracking";gpsState.startedAt=Date.now();gpsState.pausedAt=null;gpsState.watchId=navigator.geolocation.watchPosition(gpsHandlePosition,gpsHandleError,{enableHighAccuracy:true,maximumAge:3000,timeout:15000});$("gpsPauseBtn").classList.remove("hidden");$("gpsResumeBtn").classList.add("hidden");$("gpsStatus").textContent=t("activity.gps.tracking");}
async function gpsFinish(){if(!["tracking","paused"].includes(gpsState.status))return;if(gpsState.status==="tracking")gpsState.elapsedBeforePause=gpsElapsed();const elapsed=gpsState.elapsedBeforePause; if(gpsState.watchId!==null){navigator.geolocation.clearWatch(gpsState.watchId);gpsState.watchId=null;} const type=gpsState.type;const distanceKm=gpsState.distanceM/1000;const speedMs=elapsed>0?gpsState.distanceM/(elapsed/1000):0;const profileWeight=Number(profile?.weight_kg)||Number(document.querySelector('#profileForm input[name="weight_kg"]')?.value)||70;const movingSeconds=Math.round(gpsState.movingTimeMs/1000); const movingSpeed=gpsState.movingTimeMs>0?gpsState.movingDistanceM/(gpsState.movingTimeMs/1000):0; const activity={user_id:user.id,type:titleCaseGpsType(type),title:gpsActivityLabel(type),activity_at:new Date(gpsState.points[0]?.timestamp||Date.now()).toISOString(),started_at:gpsState.points[0]?.timestamp||new Date().toISOString(),ended_at:new Date().toISOString(),duration_seconds:Math.round(elapsed/1000),moving_duration_seconds:movingSeconds,distance_km:Number(distanceKm.toFixed(3)),pace_seconds_per_km:gpsPaceSec(),calories:Number(gpsCalories(type,profileWeight,elapsed,distanceKm*1000).toFixed(1)),avg_speed_kmh:Number((movingSpeed*3.6).toFixed(2)),max_speed_kmh:Number((Math.max(...gpsState.speedSamples,0)*3.6).toFixed(2)),elevation_gain_m:Number(gpsState.elevationGainM.toFixed(1)),elevation_loss_m:Number(gpsState.elevationLossM.toFixed(1)),route_data:gpsState.points,route_polyline:encodePolyline(gpsState.points),source:"gps",extraction_method:"gps",raw_data:{gps_points:gpsState.points.length,accuracy_note:"Browser Geolocation API",moving_distance_m:gpsState.movingDistanceM},image_url:null,notes:""};activity.type=({trail:"hiking",elliptical:"other"}[type]||type);try{const saved=await insertActivity(activity);pendingGpsActivity=saved;gpsState.status="finished";gpsState.watchId=null;showGpsSummary(saved);await loadActivities(user.id);toast(t("activity.gps.saved"),"ok");}catch(e){toast(e.message||t("activity.gps.saveError"),"error");}}
function titleCaseGpsType(x){return x;}
let pendingGpsActivity=null;
function showGpsSummary(a){$("gpsSummaryModal")?.classList.add("open");const set=(id,v)=>{const e=$(id);if(e)e.textContent=v;};set("gpsSummaryTitle",activityTypeLabel(a.type));set("gpsSummaryTime",formatDuration(a.duration_seconds));set("gpsSummaryDistance",formatDistance(a.distance_km));set("gpsSummaryPace",formatPace(a.pace_seconds_per_km));set("gpsSummaryCalories",`${Math.round(a.calories||0)} kcal`);set("gpsSummaryElevation",`${Math.round(a.elevation_gain_m||0)} m`);renderGpsSummaryMap(a.route_data||[]);}
function renderGpsSummaryMap(points){const el=$("gpsSummaryMap");if(!el||typeof L==="undefined")return;const m=L.map(el,{zoomControl:false}).setView(points.length?[points[0].lat,points[0].lng]:[40.4168,-3.7038],14);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(m);if(points.length){const line=L.polyline(points.map(p=>[p.lat,p.lng]),{weight:5}).addTo(m);m.fitBounds(line.getBounds(),{padding:[20,20]});}setTimeout(()=>m.invalidateSize(),100);}
function bindGps(){const sel=$("gpsActivityType"); if(sel) sel.innerHTML=GPS_ACTIVITY_TYPES.map(x=>`<option value="${x}">${escapeHtml(gpsActivityLabel(x))}</option>`).join("");$("gpsStartBtn")?.addEventListener("click",gpsStart);$("gpsPauseBtn")?.addEventListener("click",gpsPause);$("gpsResumeBtn")?.addEventListener("click",gpsResume);$("gpsFinishBtn")?.addEventListener("click",gpsFinish);$("gpsSummaryClose")?.addEventListener("click",()=>$("gpsSummaryModal")?.classList.remove("open"));["gpsSummaryModal"].forEach(id=>$("#"+id)?.addEventListener("click",e=>{if(e.target.id===id)e.currentTarget.classList.remove("open")}));setInterval(()=>{if(["tracking","paused"].includes(gpsState.status))gpsUpdateUi(true);},1000);}
