import { APP } from "./config.js";

const emptyMemory = {
  profile: {
    name: "",
    age: null,
    sex: "",
    heightCm: null,
    weightKg: null,
    level: "Intermediate",
    goal: "Recomposition",
    equipment: "",
    constraints: "",
    recovery: ""
  },
  routine: {
    version: 1,
    name: "",
    phase: "",
    week: 1,
    sessions: []
  },
  progress: {
    updatedAt: null,
    metrics: [],
    personalBests: {},
    recoveryLog: []
  },
  history: []
};

export function loadLocal() {
  try {
    const raw = localStorage.getItem(APP.storageKey);
    if (!raw) return structuredClone(emptyMemory);
    return { ...structuredClone(emptyMemory), ...JSON.parse(raw) };
  } catch {
    return structuredClone(emptyMemory);
  }
}

export function saveLocal(memory) {
  localStorage.setItem(APP.storageKey, JSON.stringify(memory));
}

export function appendHistory(memory, event) {
  const item = {
    id: crypto.randomUUID ? crypto.randomUUID() : String(Date.now()),
    timestamp: new Date().toISOString(),
    ...event
  };
  memory.history = [...(memory.history || []), item].slice(-300);
  return memory;
}

export function historyToMarkdown(memory) {
  const lines = [
    "# aOra Training History",
    "",
    "> Generated by Superhuman Coach. This file contains training/recovery notes supplied by the user or generated from app actions.",
    ""
  ];
  for (const item of memory.history || []) {
    lines.push(`## ${item.timestamp}`);
    lines.push(`**Type:** ${item.type || "note"}`);
    if (item.title) lines.push(`**Title:** ${item.title}`);
    if (item.text) lines.push("", item.text);
    lines.push("");
  }
  return lines.join("\n");
}

export function memoryPayload(memory) {
  return {
    profile: memory.profile,
    routine: memory.routine,
    progress: memory.progress,
    history: memory.history
  };
}
